Adicionando novo campo Localidade do Arquivo
fga-eps-mds/2021.2-SysArq-Frontend pull request #28
Opened 2022-03-28 19:17 UTC by Weslin-0101

Co-authored-by: <Cleberbrant> <cleberobb@hotmail.com>
Co-authored-by: <Weslin-0101> <wesleeylirac12@gmail.com>

## Descrição 

Foi adicionado um novo MenuItem chamado Localidade do Arquivo, e foi removido o campo Número!

## Issue Correspondente

[Issue91](https://github.com/fga-eps-mds/2021-2-sysarq-doc/issues/91)

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

## Anexos

## Comentários adicionais

2022-03-28 20:58 UTC, baraky requested changes
![image](https://user-images.githubusercontent.com/49804877/160485704-0a8dfe50-0c6a-41e7-afa6-7fb939061ac9.png)
Faltou atualizar na tela de Pesquisa.

2022-03-28 21:45 UTC, Weslin-0101 commented
Vou alterar agora

2022-03-28 21:51 UTC, Weslin-0101 commented
Mudança foi feita, depois dá uma olhada

2022-03-29 03:34 UTC, baraky approved these changes

2022-03-29 03:43 UTC, merged