#89 unificar assunto e tipo de documento
fga-eps-mds/2021.2-SysArq-Frontend pull request #29
Opened 2022-03-28 21:34 UTC by Gabriel-Axl

## Descrição 

Campos assunto do documento e tipo de documentos unificados

## Issue Correspondente

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

## Anexos

## Comentários adicionais

2022-03-28 21:51 UTC, Gabriel-Axl commented
A model de assunto do documento foi removida, e era utilizada apenas pelo processo administrativo, com isso não é possivel realizar o CRUD, são necessárias alterações para tornar funcional. Tipo de documento foi alterado, mas já adequamos os documentos que o utilizavam à nova model (nome de documento).

2022-03-29 13:34 UTC, black258br commented
Box foi restaurado para o padrao antes da issue pois nao conseguimos adaptar ele perfeitamente para o "nome do documento", e por isso estava dando erro nos tests, deixaremos para os meninos que forem fazer essa issue especifica nessa semana

2022-03-29 13:41 UTC, black258br commented
Com a correçao dos testes o box archiving parou de funcionar, vamos deixar para os que estao responsaveis por adaptar esse box archiving nessa semana

2022-03-31 15:44 UTC, baraky requested changes
![image](https://user-images.githubusercontent.com/49804877/161095746-77daaef3-62ac-4923-90b7-a6f08da4a136.png)
Os campos devem ser apenas: Nome do Documento e Temporalidade

2022-04-01 00:33 UTC, baraky approved these changes

2022-04-01 00:33 UTC, merged