107 adicionar unicidade campos
fga-eps-mds/2021.2-SysArq-Frontend pull request #34
Opened 2022-04-05 03:37 UTC by Weslin-0101

## Descrição 
Co-authored-by: <[Cleberbrant](https://github.com/Cleberbrant)> <[cleberobb@hotmail.com](mailto:cleberobb@hotmail.com)>
Co-authored-by: <[Weslin-0101](https://github.com/Weslin-0101)> <[wesleeylirac12@gmail.com](mailto:wesleeylirac12@gmail.com)>

Adicionando as unicidades e helpers nos campos

## Issue Correspondente

[107](https://github.com/fga-eps-mds/2021-2-SysArq-Doc/issues/107)

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

## Anexos

## Comentários adicionais

2022-04-11 05:21 UTC, baraky requested changes
Boa, ficou quase perfeito, alguns problemas identificados:

Não estou conseguindo testar o fluxo de Processo Administrativo, Arquivamento de Caixa e cadastro de Usuários. O motivo é porque a branch está atrasada comparada a devel/main e numa versão instável. Assim não consigo validar esses fluxos.

- Ao tentar cadastrar uma Relação de Frequência com o número de processo repetido o botão "Cadastrar" fica carregando infinitamente:
![image](https://user-images.githubusercontent.com/49804877/162669559-9818da32-eda7-4326-88d1-1ceb1522b53d.png)

- Ao tentar cadastrar um servidor com o CPF repetido, os campos são limpados (o único fluxo dos campos obrigatórios que faz isso), seria interessante padronizar.

2022-04-11 05:48 UTC, baraky commented
> Boa, ficou quase perfeito, alguns problemas identificados:
> 
> Não estou conseguindo testar o fluxo de Processo Administrativo, Arquivamento de Caixa e cadastro de Usuários. O motivo é porque a branch está atrasada comparada a devel/main e numa versão instável. Assim não consigo validar esses fluxos.
> 
> * Ao tentar cadastrar uma Relação de Frequência com o número de processo repetido o botão "Cadastrar" fica carregando infinitamente:
>   ![image](https://user-images.githubusercontent.com/49804877/162669559-9818da32-eda7-4326-88d1-1ceb1522b53d.png)
> * Ao tentar cadastrar um servidor com o CPF repetido, os campos são limpados (o único fluxo dos campos obrigatórios que faz isso), seria interessante padronizar.

Fiz um rebase com a devel e consegui testar os outros fluxos.

- Os outros que possuem número de processos também apresentam botão carregando infinitamente.

- Arquivamento de Caixas está retornando 500 quando tenta cadastra com um número de processo já cadastrado:
![image](https://user-images.githubusercontent.com/49804877/162671479-30adff85-50a5-4c3b-8b54-553ee4fb0d58.png)
Por isso fica o avisa de conexão em vez de duplicidade:
![image](https://user-images.githubusercontent.com/49804877/162671640-37d5fbf5-34c7-47ed-88d6-6ecf128940a0.png)


Agora o que parece ser o mais problemática, aparentemente os documentos do fluxo de Cadastro estão compartilhando o mesmo número de processo. Isso significa que se eu criar um Processo Administrativo com número de processo 1 e tentar criar uma Relação de Frequência com número de processo 1, vai acusar que já existe.

Isso acontece porque todos os documentos herdam da model Document, essa que possui o campo process_number.

![image](https://user-images.githubusercontent.com/49804877/162672187-f87cee17-5667-4d35-8827-cbe92cb00936.png)

**Entretanto** essa forma pode ser a correta, imagino que não há número de processoss iguais mesmo comparando com 2 tipos de documentos, deixaremos dessa forma e conversaremos com o Garajau quarta-feiro

2022-04-13 03:58 UTC, baraky commented
Boa. Você corrigiu o problema do carregamento infinito, mas ainda falta algumas coisas:
- O Arquivamento de Caixas está retornando 500 quando tenta cadastrar com um número do processo já cadastrado e não está sendo capturado no front (não tá aparecendo o card vermelho correto)
- O cadastro de servidor está limpando os campos quando tenta cadastrar com o CPF já cadastrado (nos outros campos obrigatórios não limpa, mater esse padrão)
- No cadastro de usuários no sistema, não está havendo o tratamento de unicidade para o CPF (apenas para username)

2022-04-14 14:20 UTC, Weslin-0101 commented
No cadastro de usuário do sistema, coloquei para um card vermelho para caso o nome de usuário já esteja em uso ou o cpf já esteja cadastrado. Essa foi a única forma que pensei em tratar esses dois campos, pois não sei como posso tratá-los individualmente, criando um card para cada um

2022-04-19 06:39 UTC, baraky approved these changes

2022-04-19 06:39 UTC, merged