Adicionar máscara do CPF no cadastro de servidor
fga-eps-mds/2021.2-SysArq-Frontend pull request #5
Opened 2022-03-07 20:50 UTC by black258br

Co-authored-by: <Wesley Lira> <wesleeylirac12@gmail.com>
Co-authored-by: <Arthur Henrique> <arthurhenrir4@gmail.com>

## Descrição 

## Issue Correspondente

## Checklist 

* [ ] Nome do pull request significativo e representa o que está sendo submetido.
* [ ] Passou nos testes de integração
* [ ] Branch de acordo com a política de gerenciamento e configuração
* [ ] Critérios de aceitação cumpridos
* [ ] Caso necessário, realizou teste correspondente às funcionalidades implementadas.
* [ ] Revisor marcado

## Anexos

## Comentários adicionais

2022-03-07 20:52 UTC, black258br commented
IMPORTANTE: É necessario aumentar o length do cpf no repositorio "Archives\archives_app\fields_models.py" de 11 para 16

PublicWorker(models.Model):
    name = models.CharField(max_length=150)
    cpf = models.CharField(max_length=16)

2022-03-09 17:27 UTC, baraky requested changes
O arquivo package.json está em sysarq/src/pages/Fields/package.json, resultando em erros ao subir o ambiente.

Transferi ele para sysarq/package.json e deu certo. Por favor corrigir isso.

2022-03-10 17:54 UTC, black258br commented
Correção do arquivo Package.json feita

2022-03-10 19:36 UTC, baraky commented
> Correção do arquivo Package.json feita

Boa, agora precisa resolver o conflito com a devel para podermos fazer o merge.

2022-03-11 14:15 UTC, black258br commented
Creio q tenha resolvido

2022-03-11 16:53 UTC, baraky approved these changes

2022-03-11 16:57 UTC, merged